export const headings = [
    "Id",
    "Name",
    "Father/Spouse Name",
    "Gender",
    "Date of Birth",
    "Blood Group",
    "Phone Number",
    "Alternate Number",
    "Whatsapp Number",
    "Email",
    "Category",
    "Profile",
    "Department",
    "Designation",
    "Religion",
    "Aadhar Number",
    "Qualification",
    "Class Preffered",
    "Subject Preffered",
    "Bank Name",
    "Bank A/C Number",
    "Bank IFSC",
    "Pan Card Number",
    "Pf Number",
    "Basic Salary",
    "HRA Amount",
    "DA Amount",
    "Allowances",
    "Other Vages",
    "PF Amount",
    "TDS Amount",
    "ESIC Amount",
    "Professional Tax",
    "Address",
    "Village",
    "Block",
    "District",
    "State",
    "Pincode",
    "Land Mark",
    "Sign Photo",
    "Experience",
    "Qualification Photo",
    "Id Proof",
    "Pan Card Photo",
    "Aadhar Card Photo"
]

export const fields = [
    'empId',
    'empName',
    'empRelativeName',
    'empGender',
    'empDOB',
    'empBloodGrp',
    'empNumberOne',
    'empNumberTwo',
    'empWhatsappNumber',
    'empEmail',
    'empCategory',
    'empProfile',
    'empDepartment',
    'empDesignation',
    'empReligion',
    'empAadharNumber',
    'empQualification',
    'empClassPreffered',
    'empSubjectPreffered',
    'empBankName',
    'empBankAcNumber',
    'empBankIfscCode',
    'empPanCardNumber',
    'empPfNumber',
    'empBasicSalary',
    'empHraAmount',
    'empDaAmount',
    'empAllowances',
    'empOtherWages',
    'empPfAmount',
    'empTdsAmount',
    'empEsicAmount',
    'empProfessionalTax',
    'empAddress',
    'empVillage',
    'empBlock',
    'empDistrict',
    'empState',
    'empPinCode',
    'empLandMark',
    'empSign',
    'empExperience',
    'empQualificationPhoto',
    'empIdProof',
    'empPanCardPhoto',
    'empAadharCardPhoto',
    'empCV'
]
