export const headings = [
    "Registeration Number",
    "Registeration Date",
    "Class",
    "Section",
    "Name",
    "Father's Name",
    "Mother's Name",
    "Phone Number",
    "Alternate Number",
    "Gender",
    "Date Of Birth",
    "Age",
    "Email",
    "Monthly Fees",
    "Address",
    "Town",
    "Landmark",
    "City",
    "District",
    "State",
    "Pincode",


]
// Define an array of fields
export const fields = [
    "registerationNumber",
    "registerationDate",
    "studentClass",
    "section",
    "studentName",
    "fatherName",
    "motherName",
    "phoneNumber",
    "alternatePhoneNumber",
    "gender",
    "dob",
    "age",
    "email",
    "monthlyFees",
    "address",
    "town",
    "landMark",
    "city",
    "district",
    "state",
    "pincode",

];
