import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SidNavBar from "@/components/Sidebar/SideBar2";
import { AiOutlineLogout} from "react-icons/ai";
import {PiStudentFill} from "react-icons/pi";
import {FaSchoolFlag} from "react-icons/fa6";
import {HiMiniUserGroup} from "react-icons/hi2";
import {GiEntryDoor} from "react-icons/gi";
import {MdOutlineBrowserUpdated} from "react-icons/md";
import {HiUserRemove} from "react-icons/hi";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function layout({children}: {
    children: React.ReactNode
}) {
    const Menus = [
        { title: "Home",icon:<FaSchoolFlag />, link: '/' },
        { title: "View Students", icon: <HiMiniUserGroup />, link: '/student-section/ViewStudents' },
        { title: "Student", spacing: true, icon: <PiStudentFill />,link: '/student-section/student/ABCd123' },
        { title: "Input Student", icon: <GiEntryDoor />, link: '/student-section/NewStudent' },
        { title: "Update Student", icon: <MdOutlineBrowserUpdated />, link: '/student-section/UpdateStudent' },
        { title: "Remove Student", icon: <HiUserRemove />, link: '/student-section/RemoveStudent' },
        { title: "Logout", icon: <AiOutlineLogout />, link: '/logout' },
    ];
    return (
        <div className={inter.className}>
            <SidNavBar child={children} Menus={Menus}/>
        </div>
    )
}
