export interface Student {
    registerationNumber: string;
    registerationDate: string;
    studentClass: number;
    image: string;
    phoneNumber: string;
    section: string;
    studentName: string;
    fatherName: string;
    motherName: string;
    gender: string;
    dob: string,
    alternatePhoneNumber: string;
    email: string;
    address: string;
    town: string;
    city: string;
    district: string;
    state: string;
    pincode: string;
    landMark: string;
    rollNumber?: number;
    aaadharNumber?: string;
    bloodGroup?: string;
    category?: string;
    religion?: string;
    lastSchoolName?: string;
    lastClass?: string;
    lastClassScore?: string;
    lastClassYear?: string;
    lastClassTC?: string;
    lastClassReason?: string;
    lastClassBoard?: string;
    lastClassMedium?: string;
    lastClassSchool?: string;
    lastClassCity?: string;
}
